// This file is automatically generated by qtc from "err.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line err.qtpl:1
package client

//line err.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line err.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line err.qtpl:2
// ErrPage is a page that holds err information.
type ErrPage struct {
	Message string
	Code    string
	Title   string
}

// Error makes ErrPage of type error.
func (e ErrPage) Error() string {
	return e.Code + ": " + e.Message
}

// NotFoundPage is an ErrPage for 404 Not Found pages.
var NotFoundPage = ErrPage{
	Message: "We're sorry but we couldn't find the page you're looking for :(",
	Code:    "Error - HTTP 404: Not Found",
	Title:   "Not it",
}

// PanicPage is an ErrPage for 500 Internal Server Error pages.
var PanicPage = ErrPage{
	Message: "There seems to be something wrong. Don't panic, we're already doing that for you.",
	Code:    "Error - HTTP 500: Internal Server Error",
	Title:   "Panicing",
}

// UnavailablePage is an ErrPage for 503 Service Unavailable pages.
var UnavailablePage = ErrPage{
	Message: "This page isn't ready just yet.",
	Code:    "Error - HTTP 503: Service Unavailable",
	Title:   "Work in process",
}

//line err.qtpl:38
func (e ErrPage) streamhead(qw422016 *qt422016.Writer) {
	//line err.qtpl:38
	qw422016.N().S(`<title>`)
	//line err.qtpl:39
	qw422016.N().S(e.Title)
	//line err.qtpl:39
	qw422016.N().S(`- Computing Fun</title><link rel="stylesheet" type="text/css" href="/client/pages/error.css">`)
//line err.qtpl:41
}

//line err.qtpl:41
func (e ErrPage) writehead(qq422016 qtio422016.Writer) {
	//line err.qtpl:41
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line err.qtpl:41
	e.streamhead(qw422016)
	//line err.qtpl:41
	qt422016.ReleaseWriter(qw422016)
//line err.qtpl:41
}

//line err.qtpl:41
func (e ErrPage) head() string {
	//line err.qtpl:41
	qb422016 := qt422016.AcquireByteBuffer()
	//line err.qtpl:41
	e.writehead(qb422016)
	//line err.qtpl:41
	qs422016 := string(qb422016.B)
	//line err.qtpl:41
	qt422016.ReleaseByteBuffer(qb422016)
	//line err.qtpl:41
	return qs422016
//line err.qtpl:41
}

//line err.qtpl:43
func (e ErrPage) streambody(qw422016 *qt422016.Writer) {
	//line err.qtpl:43
	qw422016.N().S(`<img class="icon" src="/client/ico/250r.png" alt="Computing Fun Error" height="250" width="250"><div class="message dark-theme-tag">`)
	//line err.qtpl:46
	qw422016.N().S(e.Message)
	//line err.qtpl:46
	qw422016.N().S(`</div><div class="code">`)
	//line err.qtpl:49
	qw422016.N().S(e.Code)
	//line err.qtpl:49
	qw422016.N().S(`</div>`)
//line err.qtpl:51
}

//line err.qtpl:51
func (e ErrPage) writebody(qq422016 qtio422016.Writer) {
	//line err.qtpl:51
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line err.qtpl:51
	e.streambody(qw422016)
	//line err.qtpl:51
	qt422016.ReleaseWriter(qw422016)
//line err.qtpl:51
}

//line err.qtpl:51
func (e ErrPage) body() string {
	//line err.qtpl:51
	qb422016 := qt422016.AcquireByteBuffer()
	//line err.qtpl:51
	e.writebody(qb422016)
	//line err.qtpl:51
	qs422016 := string(qb422016.B)
	//line err.qtpl:51
	qt422016.ReleaseByteBuffer(qb422016)
	//line err.qtpl:51
	return qs422016
//line err.qtpl:51
}

//line err.qtpl:53
func (e ErrPage) streamnavLinks(qw422016 *qt422016.Writer) {
//line err.qtpl:53
}

//line err.qtpl:53
func (e ErrPage) writenavLinks(qq422016 qtio422016.Writer) {
	//line err.qtpl:53
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line err.qtpl:53
	e.streamnavLinks(qw422016)
	//line err.qtpl:53
	qt422016.ReleaseWriter(qw422016)
//line err.qtpl:53
}

//line err.qtpl:53
func (e ErrPage) navLinks() string {
	//line err.qtpl:53
	qb422016 := qt422016.AcquireByteBuffer()
	//line err.qtpl:53
	e.writenavLinks(qb422016)
	//line err.qtpl:53
	qs422016 := string(qb422016.B)
	//line err.qtpl:53
	qt422016.ReleaseByteBuffer(qb422016)
	//line err.qtpl:53
	return qs422016
//line err.qtpl:53
}
