// Code generated by hero.
// source: C:\Users\zac22\go\src\gitlab.com\computingfun\computingfun.org\client\index.html
// DO NOT EDIT!
package client

import (
	"io"

	"github.com/shiyanhui/hero"
)

func Index(w io.Writer) (int, error) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>

    <body>
        `)
	_buffer.WriteString(`
    <p>Hello world!</p>
`)

	_buffer.WriteString(`
    </body>
</html>`)
	return w.Write(_buffer.Bytes())

}
