// This file is automatically generated by qtc from "index.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line index.qtpl:1
package client

//line index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line index.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line index.qtpl:1
type IndexPage struct{}

//line index.qtpl:5
func (i IndexPage) streamhead(qw422016 *qt422016.Writer) {
	//line index.qtpl:5
	qw422016.N().S(`<title>Computing Fun</title><meta name="description" content="Learn, Build, Play. Computing Fun is here to learn, teach and build games."><link rel="stylesheet" type="text/css" href="/client/pages/index.css">`)
//line index.qtpl:9
}

//line index.qtpl:9
func (i IndexPage) writehead(qq422016 qtio422016.Writer) {
	//line index.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line index.qtpl:9
	i.streamhead(qw422016)
	//line index.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line index.qtpl:9
}

//line index.qtpl:9
func (i IndexPage) head() string {
	//line index.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
	//line index.qtpl:9
	i.writehead(qb422016)
	//line index.qtpl:9
	qs422016 := string(qb422016.B)
	//line index.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
	//line index.qtpl:9
	return qs422016
//line index.qtpl:9
}

//line index.qtpl:11
func (i IndexPage) streambody(qw422016 *qt422016.Writer) {
	//line index.qtpl:11
	qw422016.N().S(`<div class="nav-boxes"><a style="background-color: #ff0000;" href="https://www.youtube.com/channel/UCeZQbACMihORscFIwmydpzA"><i class="fab fa-youtube"></i></a><a style="background-color: #f85944;" href="https://www.patreon.com/computingfun"><i class="fab fa-patreon"></i></a><a style="background-color: #171A21;" href="https://computingfun.org/games/"><i class="fas fa-gamepad"></i></a><a style="background-color: #77ab59;" href="https://computingfun.org/articles/"><i class="far fa-newspaper"></i></a><a style="background-color: #6441A4;" href="#"><i class="fab fa-twitch"></i></a></div>`)
//line index.qtpl:19
}

//line index.qtpl:19
func (i IndexPage) writebody(qq422016 qtio422016.Writer) {
	//line index.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line index.qtpl:19
	i.streambody(qw422016)
	//line index.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line index.qtpl:19
}

//line index.qtpl:19
func (i IndexPage) body() string {
	//line index.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
	//line index.qtpl:19
	i.writebody(qb422016)
	//line index.qtpl:19
	qs422016 := string(qb422016.B)
	//line index.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
	//line index.qtpl:19
	return qs422016
//line index.qtpl:19
}

//line index.qtpl:21
func (i IndexPage) streamnavLinks(qw422016 *qt422016.Writer) {
//line index.qtpl:21
}

//line index.qtpl:21
func (i IndexPage) writenavLinks(qq422016 qtio422016.Writer) {
	//line index.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line index.qtpl:21
	i.streamnavLinks(qw422016)
	//line index.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line index.qtpl:21
}

//line index.qtpl:21
func (i IndexPage) navLinks() string {
	//line index.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
	//line index.qtpl:21
	i.writenavLinks(qb422016)
	//line index.qtpl:21
	qs422016 := string(qb422016.B)
	//line index.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
	//line index.qtpl:21
	return qs422016
//line index.qtpl:21
}
