// This file is automatically generated by qtc from "page.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line page.qtpl:2
package client

//line page.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line page.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line page.qtpl:2
type Page interface {
	//line page.qtpl:2
	head() string
	//line page.qtpl:2
	streamhead(qw422016 *qt422016.Writer)
	//line page.qtpl:2
	writehead(qq422016 qtio422016.Writer)
	//line page.qtpl:2
	navLinks() string
	//line page.qtpl:2
	streamnavLinks(qw422016 *qt422016.Writer)
	//line page.qtpl:2
	writenavLinks(qq422016 qtio422016.Writer)
	//line page.qtpl:2
	body() string
	//line page.qtpl:2
	streambody(qw422016 *qt422016.Writer)
	//line page.qtpl:2
	writebody(qq422016 qtio422016.Writer)
//line page.qtpl:2
}

//line page.qtpl:11
func streamnavLink(qw422016 *qt422016.Writer, text, link, icon, color string) {
	//line page.qtpl:11
	qw422016.N().S(`<a style="background-color:`)
	//line page.qtpl:12
	qw422016.N().S(color)
	//line page.qtpl:12
	qw422016.N().S(`;" href="`)
	//line page.qtpl:12
	qw422016.N().S(link)
	//line page.qtpl:12
	qw422016.N().S(`">`)
	//line page.qtpl:12
	qw422016.N().S(text)
	//line page.qtpl:12
	qw422016.N().S(`<i class="`)
	//line page.qtpl:12
	qw422016.N().S(icon)
	//line page.qtpl:12
	qw422016.N().S(`"></i></a>`)
//line page.qtpl:13
}

//line page.qtpl:13
func writenavLink(qq422016 qtio422016.Writer, text, link, icon, color string) {
	//line page.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line page.qtpl:13
	streamnavLink(qw422016, text, link, icon, color)
	//line page.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line page.qtpl:13
}

//line page.qtpl:13
func navLink(text, link, icon, color string) string {
	//line page.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
	//line page.qtpl:13
	writenavLink(qb422016, text, link, icon, color)
	//line page.qtpl:13
	qs422016 := string(qb422016.B)
	//line page.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
	//line page.qtpl:13
	return qs422016
//line page.qtpl:13
}

//line page.qtpl:15
func StreamHTML(qw422016 *qt422016.Writer, p Page) {
	//line page.qtpl:15
	qw422016.N().S(`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="shortcut icon" href="/client/ico/fav.ico"><link rel="icon" type="image/png" href="/client/ico/192.png" sizes="192x192"><link rel="apple-touch-icon" sizes="180x180" href="/client/ico/180.png"><link rel="stylesheet" type="text/css" href="/client/base/nav.css"><link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">`)
	//line page.qtpl:27
	p.streamhead(qw422016)
	//line page.qtpl:27
	qw422016.N().S(`</head><body style="background-color: whitesmoke;"><nav class="navbar"><div>Computing Fun</div><img src="/client/ico/50.png" alt="Computing Fun" height="50" width="50">`)
	//line page.qtpl:34
	streamnavLink(qw422016, "Channel", "https://www.youtube.com/channel/UCeZQbACMihORscFIwmydpzA", "fab fa-youtube", "#ff0000")
	//line page.qtpl:35
	streamnavLink(qw422016, "Patron", "https://www.patreon.com/computingfun", "fab fa-patreon", "#f85944")
	//line page.qtpl:36
	streamnavLink(qw422016, "Games", "https://computingfun.org/games/", "fas fa-gamepad", "#171A21")
	//line page.qtpl:37
	streamnavLink(qw422016, "Articles", "https://computingfun.org/articles/", "far fa-newspaper", "#77ab59")
	//line page.qtpl:38
	streamnavLink(qw422016, "Facebook", "https://www.facebook.com/ComputingFun/", "fab fa-facebook-f", "#3B5998")
	//line page.qtpl:39
	streamnavLink(qw422016, "Live", "#", "fab fa-youtube", "#6441A4")
	//line page.qtpl:40
	p.streamnavLinks(qw422016)
	//line page.qtpl:40
	qw422016.N().S(`</nav><main style="margin: auto; width: 80%; z-index: 0;">`)
	//line page.qtpl:43
	p.streambody(qw422016)
	//line page.qtpl:43
	qw422016.N().S(`</main></body></html>`)
//line page.qtpl:48
}

//line page.qtpl:48
func WriteHTML(qq422016 qtio422016.Writer, p Page) {
	//line page.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line page.qtpl:48
	StreamHTML(qw422016, p)
	//line page.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line page.qtpl:48
}

//line page.qtpl:48
func HTML(p Page) string {
	//line page.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
	//line page.qtpl:48
	WriteHTML(qb422016, p)
	//line page.qtpl:48
	qs422016 := string(qb422016.B)
	//line page.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
	//line page.qtpl:48
	return qs422016
//line page.qtpl:48
}
