// Code generated by hero.
// source: C:\Users\zac22\go\src\gitlab.com\computingfun\www\html\err.html
// DO NOT EDIT!
package html

import (
	"io"

	"github.com/shiyanhui/hero"
)

func Err(e *ErrMessage, w io.Writer) (int, error) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html>

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="/client/ico/fav.ico">
        <link rel="icon" type="image/png" href="/client/ico/192.png" sizes="192x192">
        <link rel="apple-touch-icon" sizes="180x180" href="/client/ico/180.png">
        <link rel="stylesheet" type="text/css" href="/client/base/nav.css">
        <link rel="stylesheet" type="text/css" href="/client/base/prettyprint.css">
        <link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
        <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
        `)
	_buffer.WriteString(`
<title>
    `)
	hero.EscapeHTML(e.Title, _buffer)
	_buffer.WriteString(` - Computing Fun</title>
<link rel="stylesheet" type="text/css" href="/client/pages/error.css">
`)

	_buffer.WriteString(`
    </head>

    <body style="background-color: whitesmoke;">
        <nav class="navbar">
            <div>Computing Fun</div>
            <img src="/client/ico/50.png" alt="Computing Fun" height="50" width="50">
            <a style="background-color: green;" href="/">Check out the site<i class="fa fa-home"></i></a>
            <a style="background-color: red;" href="https://www.youtube.com/channel/UCeZQbACMihORscFIwmydpzA">See our videos<i class="fab fa-youtube"></i></a>
            <a style="background-color: #f85944;" href="https://www.patreon.com/computingfun">Become a Patron<i class="fab fa-patreon"></i></a>
            <a style="background-color: #3B5998;" href="https://www.facebook.com/ComputingFun/">Like us<i class="fab fa-facebook-f"></i></a>
            <a style="background-color: #6441A4;" href="#">See us live<i class="fab fa-twitch"></i></a>
            `)
	_buffer.WriteString(`
        </nav>
        <main style="margin: auto; width: 80%; z-index: 0;">
            `)
	_buffer.WriteString(`
<img class="icon" src="/client/ico/250r.png" alt="Computing Fun Error" height="250" width="250">
<div class="message">
    `)
	hero.EscapeHTML(e.Message, _buffer)
	_buffer.WriteString(`
</div>
<div class="code">
    `)
	hero.EscapeHTML(e.Code, _buffer)
	_buffer.WriteString(`
</div>
`)

	_buffer.WriteString(`
        </main>
    </body>

</html>`)
	return w.Write(_buffer.Bytes())

}
