// Code generated by hero.
// source: C:\Users\zac22\go\src\gitlab.com\computingfun\www\html\index.html
// DO NOT EDIT!
package html

import (
	"io"

	"github.com/shiyanhui/hero"
)

func Index(w io.Writer) (int, error) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html>

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="/client/ico/fav.ico">
        <link rel="icon" type="image/png" href="/client/ico/192.png" sizes="192x192">
        <link rel="apple-touch-icon" sizes="180x180" href="/client/ico/180.png">
        <link rel="stylesheet" type="text/css" href="/client/base/nav.css">
        <link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
        `)
	_buffer.WriteString(`
<title>Computing Fun</title>
<meta name="description" content="We build, teach and deploy all types of software solutions. From teaching non tech to developers. Building software and web servers of small businesses.">
<link rel="stylesheet" type="text/css" href="/client/pages/index.css">
`)

	_buffer.WriteString(`
    </head>

    <body style="background-color: whitesmoke;">
        <nav class="navbar">
            <div>Computing Fun</div>
            <img src="/client/ico/50.png" alt="Computing Fun" height="50" width="50">
            <a style="background-color: #ff0000;" href="https://www.youtube.com/channel/UCeZQbACMihORscFIwmydpzA">Channel<i class="fab fa-youtube"></i></a>
            <a style="background-color: #f85944;" href="https://www.patreon.com/computingfun">Patron<i class="fab fa-patreon"></i></a>
            <a style="background-color: #171A21;" href="https://computingfun.org/games/">Games<i class="fas fa-gamepad"></i></a>
            <a style="background-color: #77ab59;" href="https://computingfun.org/articles/">Articles<i class="far fa-newspaper"></i></a>
            <a style="background-color: #3B5998;" href="https://www.facebook.com/ComputingFun/">Facebook<i class="fab fa-facebook-f"></i></a>
            <a style="background-color: #6441A4;" href="#">Live<i class="fab fa-twitch"></i></a>
            `)
	_buffer.WriteString(`
        </nav>
        <main style="margin: auto; width: 80%; z-index: 0;">
            `)
	_buffer.WriteString(`
<div class="nav-boxes">
    <a style="background-color: #ff0000;" href="https://www.youtube.com/channel/UCeZQbACMihORscFIwmydpzA"><i class="fab fa-youtube"></i></a>
    <a style="background-color: #f85944;" href="https://www.patreon.com/computingfun"><i class="fab fa-patreon"></i></a>
    <a style="background-color: #171A21;" href="https://computingfun.org/games/"><i class="fas fa-gamepad"></i></a>
    <a style="background-color: #77ab59;" href="https://computingfun.org/articles/"><i class="far fa-newspaper"></i></a>
    <a style="background-color: #3B5998;" href="https://www.facebook.com/ComputingFun/"><i class="fab fa-facebook-f"></i></a>
    <a style="background-color: #6441A4;" href="#"><i class="fab fa-twitch"></i></a>
</div>
`)

	_buffer.WriteString(`
        </main>
    </body>

</html>`)
	return w.Write(_buffer.Bytes())

}
